import { PrismaClient, WorkshopType, RectifierType } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting seed (bloque 1 + bloque 2)...");

  // Check for existing data to avoid duplicates
  const existingWorkshops = await prisma.workshop.count();
  const existingRectifiers = await prisma.engineRectifier.count();

  if (existingWorkshops > 0 || existingRectifiers > 0) {
    console.log(
      `⚠️  Database already contains data (${existingWorkshops} workshops, ${existingRectifiers} rectifiers). Skipping seed.`
    );
    console.log("   To reseed, clear the database first.");
    return;
  }

  // -----------------------------
  // SEED DATA
  // -----------------------------

  const workshops = [
    {
      name: "Cavalie Automotriz",
      type: WorkshopType.MECANICO,
      description: "Instalación GLP, mecánica general y planchado-pintura",
      services: ["mecánica general", "instalación GLP", "planchado y pintura"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. José Gálvez 1469, Santa Beatriz, Cercado de Lima",
        district: "Cercado de Lima",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 265-9238",
        phoneAlt: "983-745-377",
        email: null,
        whatsapp: null,
        website: "https://cavalieautomotriz.com/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Mega Autos",
      type: WorkshopType.MULTIMARCA,
      description: "Taller multimarca, mecánica general, planchado y pintura",
      services: ["mecánica general", "planchado y pintura", "diagnóstico"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Industrial 3300, San Martín de Porres 15311, Lima",
        district: "San Martín de Porres",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "934-329-515",
        phoneAlt: null,
        email: "atencionalcliente@megaautos.com.pe",
        whatsapp: null,
        website: "https://www.megaautos.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "CEDEA MOTORS",
      type: WorkshopType.MULTIMARCA,
      description: "Taller mecánico multimarca y mantenimiento de flotas",
      services: [
        "mantenimiento preventivo",
        "mecánica general",
        "planchado y pintura",
      ],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. Horacio Cachay Díaz 365, La Victoria 15034, Lima",
        district: "La Victoria",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 225-1659",
        phoneAlt: "998-157-184",
        email: null,
        whatsapp: null,
        website: "https://cedeamotors.com/",
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 2 - Talleres adicionales (7)
    // -----------------------------
    {
      name: "Autoland Perú – Taller Chorrillos",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Mitsubishi, Fuso, Chery y BYD",
      services: ["servicio oficial", "mecánica", "diagnóstico", "garantía"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Guardia Civil 1351, Chorrillos 15064",
        district: "Chorrillos",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 619-8888",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.autoland.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Derco Center – Taller Surquillo",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Suzuki, Mazda, Renault, JAC, Haval",
      services: ["servicio oficial", "mecánica general", "diagnóstico"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Tomás Marsano 1390, Surquillo 15038",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 712-0202",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.derco.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Maquinarias S.A. Toyota – Taller La Molina",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Toyota / Lexus",
      services: ["mecánica", "garantías", "diagnóstico", "mantenimiento"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. La Molina 1085, La Molina 15024",
        district: "La Molina",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 613-2323",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.toyotaperu.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Taller Automotriz WOLF",
      type: WorkshopType.MECANICO,
      description: "Especialistas en diagnóstico y reparación avanzada",
      services: ["mecánica general", "diagnóstico computarizado"],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. Los Ruiseñores 348, Santa Anita 15009",
        district: "Santa Anita",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 386-4822",
        phoneAlt: "944-969-666",
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Tecnimotores Surquillo",
      type: WorkshopType.MECANICO,
      description: "Mecánica general y mantenimiento preventivo",
      services: ["mecánica", "mantenimiento", "eléctrico"],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. Huáscar 1571, Surquillo 15048",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 241-0313",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Motormaq Perú – Taller Cercado",
      type: WorkshopType.MECANICO,
      description: "Taller especializado en mecánica ligera y media",
      services: ["mecánica ligera", "escaneo", "eléctrico automotriz"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Venezuela 1490, Cercado de Lima 15082",
        district: "Cercado de Lima",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 424-9512",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://motormaqperu.com/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Taller Automotriz IPSA Callao",
      type: WorkshopType.MULTIMARCA,
      description: "Servicio automotriz multimarca en el Callao",
      services: ["mecánica general", "aire acondicionado", "escaneo"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Óscar R. Benavides 4580, Callao 07001",
        district: "Callao",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 465-3285",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 3 - Talleres oficiales adicionales (9)
    // -----------------------------
    {
      name: "Derco Center – Taller Ate",
      type: WorkshopType.MULTIMARCA,
      description: "Servicio oficial Derco: Suzuki, Mazda, Renault, Haval, Changan",
      services: [
        "mecánica general",
        "mantenimiento preventivo",
        "servicios oficiales",
      ],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Separadora Industrial 1518, Ate 15012, Lima",
        district: "Ate",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 619-5100",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.derco.com.pe/servicios/talleres",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Toyota Mitsui – Taller La Victoria",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Toyota",
      services: ["mecánica", "repuestos", "mantenimiento Toyota"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Nicolás Arriola 500, La Victoria 15034, Lima",
        district: "La Victoria",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 612-3100",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.mitsui.com.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Hyundai Automotores Gildemeister – Taller Surquillo",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Hyundai",
      services: ["mantenimiento Hyundai", "mecánica", "eléctrica"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Tomás Marsano 1390, Surquillo 15038, Lima",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 618-5040",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.hyundai.com.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Mitsubishi – Maquinarias S.A. (Taller Surquillo)",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Mitsubishi",
      services: ["mecánica", "eléctrica", "mantenimiento Mitsubishi"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. República de Panamá 4295, Surquillo 15048, Lima",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 213-6000",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.maquinarias.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Nissan Perú – Taller La Marina",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Nissan",
      services: ["mecánica", "mantenimiento", "scanner"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. La Marina 3235, Pueblo Libre 15084, Lima",
        district: "Pueblo Libre",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 618-0200",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.nissan.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Honda Autoespar – Taller Chorrillos",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Honda",
      services: ["mantenimiento Honda", "mecánica", "diagnósticos"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Defensores del Morro 650, Chorrillos 15064, Lima",
        district: "Chorrillos",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 630-3010",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.hondaautoespar.com.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Euromotors Audi – Taller Surco",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Audi",
      services: ["Audi service", "mecánica", "electrónica", "garantía"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. El Polo 1117, Santiago de Surco 15023, Lima",
        district: "Santiago de Surco",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 630-3000",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.audi.com.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "BMW – Inchcape Service Center Surco",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial BMW",
      services: ["mantenimiento BMW", "scanner", "reparación avanzada"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Manuel Olguín 325, Surco 15023, Lima",
        district: "Santiago de Surco",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 616-2500",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.bmw.com.pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Kia – Taller Derby (Astara)",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Kia",
      services: ["diagnóstico", "mantenimiento", "mecánica ligera"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Manuel Olguín 375, Surco 15023, Lima",
        district: "Santiago de Surco",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 630-7272",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.kia.com/pe",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Mazda – Taller Ate (Derco)",
      type: WorkshopType.OFICIAL,
      description: "Servicio oficial Mazda",
      services: ["mantenimiento Mazda", "mecánica", "eléctrica"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Separadora Industrial 2100, Ate 15012, Lima",
        district: "Ate",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 619-5100",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://www.mazda.pe",
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 4 - Talleres adicionales verificados (3)
    // -----------------------------
    {
      name: "Germania Automotriz",
      type: WorkshopType.MECANICO,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Angamos Este 1869, Surquillo, Lima",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "977 155 088",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Innova Car Service",
      type: WorkshopType.MECANICO,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. San Agustín 940, Surquillo, Lima",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "973 273 554",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Mecánicos a Domicilio en Lima – 24 Horas",
      type: WorkshopType.A_DOMICILIO,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. Loreto 665, Lima 15082",
        district: "Cercado de Lima",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: null,
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 5 - Talleres adicionales verificados (7)
    // -----------------------------
    {
      name: "GLF Automotriz",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Antonio José de Sucre 558, Magdalena del Mar 15086",
        district: "Magdalena del Mar",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 2631020",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: "https://www.facebook.com/glfautomotriz",
        instagram: null,
      },
    },
    {
      name: "GLF Automotriz - Lurín",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street:
          "Calle 3 Mz O Lt 4, Urb. Nuevo Lurín, Antigua Panamericana Sur Km 29.5",
        district: "Lurín",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "263-1020",
        phoneAlt: "998-368-581",
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Multicar Audaz - Ate",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Calle 2 Mz B Lote 5, Urb. Industrial La Merced – Ate",
        district: "Ate",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "51 348-5560",
        phoneAlt: null,
        email: "servicioalcliente@multicaraudaz.com",
        whatsapp: null,
        website: "https://multicaraudaz.com/",
        facebook: null,
        instagram: "@multicaraudaz.pe",
      },
    },
    {
      name: "Multicar Audaz - Comas",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Trapiche 831, Comas (Paradero «Pinar»)",
        district: "Comas",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "51 535-0531",
        phoneAlt: null,
        email: "servicioalcliente@multicaraudaz.com",
        whatsapp: null,
        website: "https://multicaraudaz.com/",
        facebook: null,
        instagram: "@multicaraudaz.pe",
      },
    },
    {
      name: "Corfigas Taller Automotriz Surquillo",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Angamos Este 868 - Surquillo",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "920861192",
        phoneAlt: null,
        email: "ventas.corfigas@hotmail.com",
        whatsapp: null,
        website: "https://tallerautomotrizcorfigasingenieros.com/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Germania Automotriz - San Luis",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. San Luis 824 - San Luis",
        district: "San Luis",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "977 155 088",
        phoneAlt: null,
        email: "sanluis@germania.com.pe",
        whatsapp: null,
        website: "https://www.germania.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Germania Automotriz - La Molina",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. La Molina 656 - La Molina",
        district: "La Molina",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "977 155 088",
        phoneAlt: null,
        email: "lamolina@germania.com.pe",
        whatsapp: null,
        website: "https://www.germania.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 6 - Talleres adicionales verificados (3)
    // -----------------------------
    {
      name: "Automotriz Lima Sur",
      type: WorkshopType.MECANICO,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street:
          "Jr Daniel Alcides Carrión Mz R Lt 1A AAHH 19 de Julio, Villa María del Trinfo, Lima",
        district: "Villa María del Trunfo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "994 422 368",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Taller Automotriz Corfigas Ingenieros",
      type: WorkshopType.MULTIMARCA,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Angamos Este 868, Surquillo, Lima",
        district: "Surquillo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: null,
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "https://tallerautomotrizcorfigasingenieros.com/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Mecánica Minertex Perú",
      type: WorkshopType.MECANICO,
      description: null,
      services: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Mz K Lt.6, Villa María del Trunfo 15023, Lima",
        district: "Villa María del Trunfo",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: null,
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
  ];

  // -----------------------------
  // RECTIFICADORAS (BLOQUE 2 + BLOQUE 4 + BLOQUE 5 + BLOQUE 6)
  // -----------------------------

  const rectifiers = [
    {
      name: "Rectificaciones Ingeniería Diesel Perú",
      type: RectifierType.DIESEL,
      description: "Rectificación de motores diesel de trabajo pesado",
      specialties: ["rectificación", "cigüeñales", "camisas"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Argentina 4450, Callao 07031",
        district: "Callao",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 465-2348",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: "http://www.ingenieriaperu.com.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Rectificadora Perú Motor",
      type: RectifierType.RECTIFICADORA,
      description: "Rectificado de bloques, culatas y cigüeñales",
      specialties: ["rectificado de motor", "bloques", "culatas"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Nicolás Arriola 871, La Victoria 15034",
        district: "La Victoria",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 224-6373",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Rectificaciones Motor Power",
      type: RectifierType.RECTIFICADORA,
      description: "Rectificación completa de motores gasolina y diesel",
      specialties: ["rectificación", "cigüeñales", "camisas", "culatas"],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. México 1240, La Victoria 15034",
        district: "La Victoria",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 431-2707",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 4 - Rectificadoras adicionales verificadas (2)
    // -----------------------------
    {
      name: "Rectificaciones Emanuel SG",
      type: RectifierType.RECTIFICADORA,
      description: null,
      specialties: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Los Chancas 1538, Urb. Los Productores Santa Anita, Lima",
        district: "Santa Anita",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: null,
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Rectificaciones Rivera Diesel Motors S.A.C.",
      type: RectifierType.DIESEL,
      description: null,
      specialties: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Av. Calca 239, Coop. 27 de Abril, Ate Vitarte, Lima",
        district: "Ate",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "(01) 349 4178",
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 5 - Rectificadoras adicionales verificadas (3)
    // -----------------------------
    {
      name: "Montalvo compresores y motores eléctricos",
      type: RectifierType.COMPRESORES,
      description: null,
      specialties: [
        "rectificación de cigueñales de compresor",
        "encamisado y rectificado de cilindros de compresor",
        "rectificación de tapas de motores",
      ],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. Alemania 2267, Cercado de Lima",
        district: "Cercado de Lima",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "51 425 5377",
        phoneAlt: null,
        email: "ventas@rebmontalvo.pe",
        whatsapp: "998107377",
        website: "https://rebmontalvo.pe/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "Rectificaciones American Diesel Motors",
      type: RectifierType.DIESEL,
      description: null,
      specialties: [
        "rectificación de motores",
        "mantenimiento y reconstrucción de maquinaria pesada",
        "fabricación de piezas en general",
      ],
      rating: null,
      tenantId: null,
      address: {
        street:
          "Av. Próceres de la Independencia N° 1305 - 1313, Urb. Los Jardines",
        district: "San Juan de Lurigancho",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "01 322-7070",
        phoneAlt: "953-108-671 / 994-087-566",
        email: "rectificacionesamerican@gmail.com",
        whatsapp: null,
        website: "https://www.rectificacionesamericandiesel.com/",
        facebook: null,
        instagram: null,
      },
    },
    {
      name: "G Y R Rectificadora de Motores",
      type: RectifierType.RECTIFICADORA,
      description: null,
      specialties: [],
      rating: null,
      tenantId: null,
      address: {
        street: "CAL. GARCIA NARANJO NRO. 433",
        district: "La Victoria",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: null,
        phoneAlt: null,
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
    // -----------------------------
    // BLOQUE 6 - Rectificadora adicional verificada (1)
    // -----------------------------
    {
      name: "WS Rectificaciones S.A.C.",
      type: RectifierType.RECTIFICADORA,
      description: null,
      specialties: [],
      rating: null,
      tenantId: null,
      address: {
        street: "Jr. Aguarico 1153, Breña, Lima",
        district: "Breña",
        province: "Lima",
        country: "Perú",
        latitude: null,
        longitude: null,
      },
      contact: {
        phone: "331 2857",
        phoneAlt: "998 059 383",
        email: null,
        whatsapp: null,
        website: null,
        facebook: null,
        instagram: null,
      },
    },
  ];

  // -----------------------------
  // SEED INSERTIONS
  // -----------------------------

  let createdWorkshops = 0;
  let createdRectifiers = 0;

  console.log("📦 Seeding workshops...");
  for (const w of workshops) {
    try {
      await prisma.workshop.create({
        data: {
          name: w.name,
          type: w.type,
          description: w.description ?? undefined,
          services: w.services,
          rating: w.rating ?? undefined,
          tenantId: w.tenantId ?? undefined,
          address: {
            create: {
              street: w.address.street ?? undefined,
              district: w.address.district,
              province: w.address.province,
              country: w.address.country,
              latitude: w.address.latitude ?? undefined,
              longitude: w.address.longitude ?? undefined,
            },
          },
          contact: {
            create: {
              phone: w.contact.phone ?? undefined,
              phoneAlt: w.contact.phoneAlt ?? undefined,
              email: w.contact.email ?? undefined,
              whatsapp: w.contact.whatsapp ?? undefined,
              website: w.contact.website ?? undefined,
              facebook: w.contact.facebook ?? undefined,
              instagram: w.contact.instagram ?? undefined,
            },
          },
        },
      });
      createdWorkshops++;
      console.log(`✅ Created workshop: ${w.name}`);
    } catch (error) {
      console.error(`❌ Error creating workshop "${w.name}":`, error);
    }
  }

  console.log("📦 Seeding rectifiers...");
  for (const r of rectifiers) {
    try {
      await prisma.engineRectifier.create({
        data: {
          name: r.name,
          type: r.type,
          description: r.description ?? undefined,
          specialties: r.specialties,
          rating: r.rating ?? undefined,
          tenantId: r.tenantId ?? undefined,
          address: {
            create: {
              street: r.address.street ?? undefined,
              district: r.address.district,
              province: r.address.province,
              country: r.address.country,
              latitude: r.address.latitude ?? undefined,
              longitude: r.address.longitude ?? undefined,
            },
          },
          contact: {
            create: {
              phone: r.contact.phone ?? undefined,
              phoneAlt: r.contact.phoneAlt ?? undefined,
              email: r.contact.email ?? undefined,
              whatsapp: r.contact.whatsapp ?? undefined,
              website: r.contact.website ?? undefined,
              facebook: r.contact.facebook ?? undefined,
              instagram: r.contact.instagram ?? undefined,
            },
          },
        },
      });
      createdRectifiers++;
      console.log(`✅ Created rectifier: ${r.name}`);
    } catch (error) {
      console.error(`❌ Error creating rectifier "${r.name}":`, error);
    }
  }

  console.log(
    `✅ Seed completed: ${createdWorkshops} workshops, ${createdRectifiers} rectifiers created.`
  );
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
